### ISSUE TITLE
Incorrect vendor prefix identification

### ISSUE THREAD

**Issue by crstauf** [yuschick/stylelint-plugin-defensive-css#26]
**Describe the bug**
Error `Separate different vendor prefixes into their own rules.` is showing on SASS that has no vendor prefixes:

```scss
.menu-item {

	&.menu-item-has-children::after,
	&.menu-item-has-grandchildren::after {
		content: '';
		position: absolute;
		top: 24px;
		right: 30px;
		width: 18px;
		height: 18px;
		background-size: contain;
	}
	
}
```

**To Reproduce**
1. Add the SASS code above into a sass/scss file
2. Run Stylelint with `use-defensive-css` plugin
3. Notice errors

**Expected behavior**
No vendor error(s).

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: NA
 - Version: Sonoma 14.2

**Additional context**

`package.json`
```json
{
  "devDependencies": {
    "stylelint": "^15.10.2",
    "stylelint-config-standard": "^34.0.0",
    "stylelint-config-standard-scss": "^11.1.0",
    "stylelint-high-performance-animation": "^1.9.0",
    "stylelint-order": "^6.0.3",
    "stylelint-plugin-defensive-css": "^0.9.1",
    "stylelint-stylistic": "^0.4.3"
  }
```
