### ISSUE TITLE
Grouping Selector Rule

### ISSUE THREAD

**Issue by coliff** [yuschick/stylelint-plugin-defensive-css#38]
**Describe the bug**
With the following CSS

```css
input[type='search']::-webkit-search-cancel-button,
input[type='search']::-webkit-search-decoration {
  -webkit-appearance: none;
  appearance: none;
}
```  

![image](https://github.com/yuschick/stylelint-plugin-defensive-css/assets/1212885/a6794bbd-6f56-42c0-9d42-65fdbd7c00e7)

I don't expect this to generate a warning about grouped selectors since they are both webkit. 

**Expected behavior**
I think This plugin should ignore grouped vendor prefixed selectors in this case.

**Details**

I am using an older version of this plugin (v0.10.4) as I need to use Stylelint v15. Sorry if this was fixed in a newer update and I didn't realize. :-)  It would be good to have a changelog / release notes somewhere
